# Project
create_project AXI4S_Replicator -in_memory -part xc7vx485tffg1157-1 -ip
set_property target_language VHDL [current_project]
set_property simulator_language VHDL [current_project]
set_property target_simulator XSim [current_project]
set_property ip_repo_paths [list ./IPs] [current_project]
add_files -norecurse {./Sources/AXI4S-Replicator/AXI4S_Replicator.vhd}
set_property top AXI4S_Replicator [current_fileset]

# Create IP
ipx::package_project -root_dir ./IPs/AXI4-Replicator -import_files {./Sources/AXI4S-Replicator/AXI4S_Replicator.vhd} -vendor mohammad.ewais.ca -library ME_IPs -taxonomy {/AXI_Infrastructure}
set_property vendor_display_name {Mohammad Ewais} [ipx::current_core]
set_property name AXI4S_Replicator [ipx::current_core]
set_property display_name {AXI4 Stream Replicator v1.0} [ipx::current_core]
set_property description {AXI4 Stream Replicator} [ipx::current_core]
set_property company_url {http://mohammad.ewais.ca} [ipx::current_core]
set_property vendor_display_name {Mohammad Ewais} [ipx::current_core]
set_property supported_families {virtex7 Production qvirtex7 Production kintex7 Production kintex7l Production qkintex7 Production qkintex7l Production artix7 Production artix7l Production aartix7 Production qartix7 Production zynq Production qzynq Production azynq Production spartan7 Production aspartan7 Production virtexu Production zynquplus Production virtexuplus Production virtexuplusHBM Production kintexuplus Production kintexu Production} [ipx::current_core]

set_property widget {comboBox} [ipgui::get_guiparamspec -name "DATA_WIDTH" -component [ipx::current_core] ]
set_property value 8 [ipx::get_user_parameters DATA_WIDTH -of_objects [ipx::current_core]]
set_property value 8 [ipx::get_hdl_parameters DATA_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_type list [ipx::get_user_parameters DATA_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_list {8 16 32 64 128 256 512} [ipx::get_user_parameters DATA_WIDTH -of_objects [ipx::current_core]]
ipx::add_user_parameter REPLICAS [ipx::current_core]
set_property value_resolve_type user [ipx::get_user_parameters REPLICAS -of_objects [ipx::current_core]]
ipgui::add_param -name {REPLICAS} -component [ipx::current_core]
set_property display_name {Replicas} [ipgui::get_guiparamspec -name "REPLICAS" -component [ipx::current_core] ]
set_property tooltip {Number of replicas to create} [ipgui::get_guiparamspec -name "REPLICAS" -component [ipx::current_core] ]
set_property widget {textEdit} [ipgui::get_guiparamspec -name "REPLICAS" -component [ipx::current_core] ]
set_property value 4 [ipx::get_user_parameters REPLICAS -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_user_parameters REPLICAS -of_objects [ipx::current_core]]
set_property value_validation_type range_long [ipx::get_user_parameters REPLICAS -of_objects [ipx::current_core]]
set_property value_validation_range_minimum 2 [ipx::get_user_parameters REPLICAS -of_objects [ipx::current_core]]
set_property value_validation_range_maximum 99 [ipx::get_user_parameters REPLICAS -of_objects [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 0 [ipgui::get_guiparamspec -name "REPLICAS" -component [ipx::current_core]] -parent [ipgui::get_pagespec -name "Page 0" -component [ipx::current_core]]

ipx::infer_bus_interface M02_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 2} [ipx::get_bus_interfaces M02_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 2} [ipx::get_bus_interfaces M02_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 2} [ipx::get_bus_interfaces M02_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M03_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 3} [ipx::get_bus_interfaces M03_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 3} [ipx::get_bus_interfaces M03_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 3} [ipx::get_bus_interfaces M03_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M04_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 4} [ipx::get_bus_interfaces M04_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 4} [ipx::get_bus_interfaces M04_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 4} [ipx::get_bus_interfaces M04_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M05_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 5} [ipx::get_bus_interfaces M05_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 5} [ipx::get_bus_interfaces M05_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 5} [ipx::get_bus_interfaces M05_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M06_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 6} [ipx::get_bus_interfaces M06_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 6} [ipx::get_bus_interfaces M06_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 6} [ipx::get_bus_interfaces M06_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M07_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 7} [ipx::get_bus_interfaces M07_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 7} [ipx::get_bus_interfaces M07_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 7} [ipx::get_bus_interfaces M07_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M08_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 8} [ipx::get_bus_interfaces M08_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 8} [ipx::get_bus_interfaces M08_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 8} [ipx::get_bus_interfaces M08_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M09_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 9} [ipx::get_bus_interfaces M09_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 9} [ipx::get_bus_interfaces M09_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 9} [ipx::get_bus_interfaces M09_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M10_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 10} [ipx::get_bus_interfaces M10_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 10} [ipx::get_bus_interfaces M10_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 10} [ipx::get_bus_interfaces M10_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M11_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 11} [ipx::get_bus_interfaces M11_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 11} [ipx::get_bus_interfaces M11_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 11} [ipx::get_bus_interfaces M11_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M12_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 12} [ipx::get_bus_interfaces M12_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 12} [ipx::get_bus_interfaces M12_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 12} [ipx::get_bus_interfaces M12_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M13_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 13} [ipx::get_bus_interfaces M13_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 13} [ipx::get_bus_interfaces M13_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 13} [ipx::get_bus_interfaces M13_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M14_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 14} [ipx::get_bus_interfaces M14_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 14} [ipx::get_bus_interfaces M14_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 14} [ipx::get_bus_interfaces M14_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M15_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 15} [ipx::get_bus_interfaces M15_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 15} [ipx::get_bus_interfaces M15_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 15} [ipx::get_bus_interfaces M15_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M16_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 16} [ipx::get_bus_interfaces M16_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 16} [ipx::get_bus_interfaces M16_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 16} [ipx::get_bus_interfaces M16_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M17_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 17} [ipx::get_bus_interfaces M17_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 17} [ipx::get_bus_interfaces M17_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 17} [ipx::get_bus_interfaces M17_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M18_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 18} [ipx::get_bus_interfaces M18_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 18} [ipx::get_bus_interfaces M18_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 18} [ipx::get_bus_interfaces M18_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M19_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 19} [ipx::get_bus_interfaces M19_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 19} [ipx::get_bus_interfaces M19_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 19} [ipx::get_bus_interfaces M19_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M20_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 20} [ipx::get_bus_interfaces M20_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 20} [ipx::get_bus_interfaces M20_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 20} [ipx::get_bus_interfaces M20_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M21_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 21} [ipx::get_bus_interfaces M21_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 21} [ipx::get_bus_interfaces M21_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 21} [ipx::get_bus_interfaces M21_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M22_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 22} [ipx::get_bus_interfaces M22_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 22} [ipx::get_bus_interfaces M22_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 22} [ipx::get_bus_interfaces M22_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M23_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 23} [ipx::get_bus_interfaces M23_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 23} [ipx::get_bus_interfaces M23_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 23} [ipx::get_bus_interfaces M23_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M24_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 24} [ipx::get_bus_interfaces M24_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 24} [ipx::get_bus_interfaces M24_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 24} [ipx::get_bus_interfaces M24_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M25_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 25} [ipx::get_bus_interfaces M25_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 25} [ipx::get_bus_interfaces M25_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 25} [ipx::get_bus_interfaces M25_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M26_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 26} [ipx::get_bus_interfaces M26_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 26} [ipx::get_bus_interfaces M26_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 26} [ipx::get_bus_interfaces M26_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M27_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 27} [ipx::get_bus_interfaces M27_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 27} [ipx::get_bus_interfaces M27_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 27} [ipx::get_bus_interfaces M27_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M28_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 28} [ipx::get_bus_interfaces M28_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 28} [ipx::get_bus_interfaces M28_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 28} [ipx::get_bus_interfaces M28_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M29_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 29} [ipx::get_bus_interfaces M29_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 29} [ipx::get_bus_interfaces M29_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 29} [ipx::get_bus_interfaces M29_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M30_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 30} [ipx::get_bus_interfaces M30_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 30} [ipx::get_bus_interfaces M30_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 30} [ipx::get_bus_interfaces M30_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M31_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 31} [ipx::get_bus_interfaces M31_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 31} [ipx::get_bus_interfaces M31_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 31} [ipx::get_bus_interfaces M31_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M32_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 32} [ipx::get_bus_interfaces M32_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 32} [ipx::get_bus_interfaces M32_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 32} [ipx::get_bus_interfaces M32_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M33_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 33} [ipx::get_bus_interfaces M33_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 33} [ipx::get_bus_interfaces M33_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 33} [ipx::get_bus_interfaces M33_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M34_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 34} [ipx::get_bus_interfaces M34_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 34} [ipx::get_bus_interfaces M34_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 34} [ipx::get_bus_interfaces M34_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M35_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 35} [ipx::get_bus_interfaces M35_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 35} [ipx::get_bus_interfaces M35_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 35} [ipx::get_bus_interfaces M35_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M36_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 36} [ipx::get_bus_interfaces M36_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 36} [ipx::get_bus_interfaces M36_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 36} [ipx::get_bus_interfaces M36_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M37_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 37} [ipx::get_bus_interfaces M37_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 37} [ipx::get_bus_interfaces M37_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 37} [ipx::get_bus_interfaces M37_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M38_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 38} [ipx::get_bus_interfaces M38_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 38} [ipx::get_bus_interfaces M38_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 38} [ipx::get_bus_interfaces M38_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M39_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 39} [ipx::get_bus_interfaces M39_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 39} [ipx::get_bus_interfaces M39_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 39} [ipx::get_bus_interfaces M39_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M40_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 40} [ipx::get_bus_interfaces M40_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 40} [ipx::get_bus_interfaces M40_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 40} [ipx::get_bus_interfaces M40_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M41_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 41} [ipx::get_bus_interfaces M41_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 41} [ipx::get_bus_interfaces M41_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 41} [ipx::get_bus_interfaces M41_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M42_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 42} [ipx::get_bus_interfaces M42_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 42} [ipx::get_bus_interfaces M42_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 42} [ipx::get_bus_interfaces M42_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M43_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 43} [ipx::get_bus_interfaces M43_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 43} [ipx::get_bus_interfaces M43_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 43} [ipx::get_bus_interfaces M43_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M44_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 44} [ipx::get_bus_interfaces M44_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 44} [ipx::get_bus_interfaces M44_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 44} [ipx::get_bus_interfaces M44_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M45_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 45} [ipx::get_bus_interfaces M45_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 45} [ipx::get_bus_interfaces M45_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 45} [ipx::get_bus_interfaces M45_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M46_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 46} [ipx::get_bus_interfaces M46_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 46} [ipx::get_bus_interfaces M46_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 46} [ipx::get_bus_interfaces M46_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M47_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 47} [ipx::get_bus_interfaces M47_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 47} [ipx::get_bus_interfaces M47_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 47} [ipx::get_bus_interfaces M47_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M48_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 48} [ipx::get_bus_interfaces M48_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 48} [ipx::get_bus_interfaces M48_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 48} [ipx::get_bus_interfaces M48_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M49_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 49} [ipx::get_bus_interfaces M49_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 49} [ipx::get_bus_interfaces M49_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 49} [ipx::get_bus_interfaces M49_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M50_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 50} [ipx::get_bus_interfaces M50_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 50} [ipx::get_bus_interfaces M50_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 50} [ipx::get_bus_interfaces M50_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M51_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 51} [ipx::get_bus_interfaces M51_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 51} [ipx::get_bus_interfaces M51_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 51} [ipx::get_bus_interfaces M51_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M52_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 52} [ipx::get_bus_interfaces M52_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 52} [ipx::get_bus_interfaces M52_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 52} [ipx::get_bus_interfaces M52_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M53_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 53} [ipx::get_bus_interfaces M53_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 53} [ipx::get_bus_interfaces M53_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 53} [ipx::get_bus_interfaces M53_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M54_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 54} [ipx::get_bus_interfaces M54_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 54} [ipx::get_bus_interfaces M54_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 54} [ipx::get_bus_interfaces M54_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M55_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 55} [ipx::get_bus_interfaces M55_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 55} [ipx::get_bus_interfaces M55_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 55} [ipx::get_bus_interfaces M55_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M56_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 56} [ipx::get_bus_interfaces M56_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 56} [ipx::get_bus_interfaces M56_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 56} [ipx::get_bus_interfaces M56_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M57_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 57} [ipx::get_bus_interfaces M57_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 57} [ipx::get_bus_interfaces M57_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 57} [ipx::get_bus_interfaces M57_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M58_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 58} [ipx::get_bus_interfaces M58_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 58} [ipx::get_bus_interfaces M58_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 58} [ipx::get_bus_interfaces M58_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M59_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 59} [ipx::get_bus_interfaces M59_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 59} [ipx::get_bus_interfaces M59_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 59} [ipx::get_bus_interfaces M59_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M60_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 60} [ipx::get_bus_interfaces M60_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 60} [ipx::get_bus_interfaces M60_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 60} [ipx::get_bus_interfaces M60_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M61_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 61} [ipx::get_bus_interfaces M61_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 61} [ipx::get_bus_interfaces M61_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 61} [ipx::get_bus_interfaces M61_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M62_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 62} [ipx::get_bus_interfaces M62_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 62} [ipx::get_bus_interfaces M62_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 62} [ipx::get_bus_interfaces M62_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M63_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 63} [ipx::get_bus_interfaces M63_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 63} [ipx::get_bus_interfaces M63_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 63} [ipx::get_bus_interfaces M63_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M64_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 64} [ipx::get_bus_interfaces M64_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 64} [ipx::get_bus_interfaces M64_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 64} [ipx::get_bus_interfaces M64_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M65_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 65} [ipx::get_bus_interfaces M65_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 65} [ipx::get_bus_interfaces M65_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 65} [ipx::get_bus_interfaces M65_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M66_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 66} [ipx::get_bus_interfaces M66_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 66} [ipx::get_bus_interfaces M66_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 66} [ipx::get_bus_interfaces M66_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M67_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 67} [ipx::get_bus_interfaces M67_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 67} [ipx::get_bus_interfaces M67_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 67} [ipx::get_bus_interfaces M67_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M68_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 68} [ipx::get_bus_interfaces M68_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 68} [ipx::get_bus_interfaces M68_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 68} [ipx::get_bus_interfaces M68_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M69_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 69} [ipx::get_bus_interfaces M69_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 69} [ipx::get_bus_interfaces M69_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 69} [ipx::get_bus_interfaces M69_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M70_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 70} [ipx::get_bus_interfaces M70_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 70} [ipx::get_bus_interfaces M70_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 70} [ipx::get_bus_interfaces M70_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M71_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 71} [ipx::get_bus_interfaces M71_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 71} [ipx::get_bus_interfaces M71_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 71} [ipx::get_bus_interfaces M71_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M72_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 72} [ipx::get_bus_interfaces M72_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 72} [ipx::get_bus_interfaces M72_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 72} [ipx::get_bus_interfaces M72_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M73_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 73} [ipx::get_bus_interfaces M73_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 73} [ipx::get_bus_interfaces M73_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 73} [ipx::get_bus_interfaces M73_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M74_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 74} [ipx::get_bus_interfaces M74_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 74} [ipx::get_bus_interfaces M74_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 74} [ipx::get_bus_interfaces M74_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M75_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 75} [ipx::get_bus_interfaces M75_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 75} [ipx::get_bus_interfaces M75_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 75} [ipx::get_bus_interfaces M75_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M76_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 76} [ipx::get_bus_interfaces M76_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 76} [ipx::get_bus_interfaces M76_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 76} [ipx::get_bus_interfaces M76_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M77_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 77} [ipx::get_bus_interfaces M77_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 77} [ipx::get_bus_interfaces M77_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 77} [ipx::get_bus_interfaces M77_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M78_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 78} [ipx::get_bus_interfaces M78_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 78} [ipx::get_bus_interfaces M78_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 78} [ipx::get_bus_interfaces M78_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M79_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 79} [ipx::get_bus_interfaces M79_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 79} [ipx::get_bus_interfaces M79_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 79} [ipx::get_bus_interfaces M79_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M80_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 80} [ipx::get_bus_interfaces M80_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 80} [ipx::get_bus_interfaces M80_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 80} [ipx::get_bus_interfaces M80_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M81_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 81} [ipx::get_bus_interfaces M81_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 81} [ipx::get_bus_interfaces M81_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 81} [ipx::get_bus_interfaces M81_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M82_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 82} [ipx::get_bus_interfaces M82_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 82} [ipx::get_bus_interfaces M82_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 82} [ipx::get_bus_interfaces M82_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M83_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 83} [ipx::get_bus_interfaces M83_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 83} [ipx::get_bus_interfaces M83_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 83} [ipx::get_bus_interfaces M83_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M84_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 84} [ipx::get_bus_interfaces M84_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 84} [ipx::get_bus_interfaces M84_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 84} [ipx::get_bus_interfaces M84_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M85_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 85} [ipx::get_bus_interfaces M85_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 85} [ipx::get_bus_interfaces M85_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 85} [ipx::get_bus_interfaces M85_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M86_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 86} [ipx::get_bus_interfaces M86_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 86} [ipx::get_bus_interfaces M86_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 86} [ipx::get_bus_interfaces M86_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M87_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 87} [ipx::get_bus_interfaces M87_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 87} [ipx::get_bus_interfaces M87_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 87} [ipx::get_bus_interfaces M87_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M88_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 88} [ipx::get_bus_interfaces M88_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 88} [ipx::get_bus_interfaces M88_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 88} [ipx::get_bus_interfaces M88_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M89_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 89} [ipx::get_bus_interfaces M89_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 89} [ipx::get_bus_interfaces M89_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 89} [ipx::get_bus_interfaces M89_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M90_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 90} [ipx::get_bus_interfaces M90_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 90} [ipx::get_bus_interfaces M90_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 90} [ipx::get_bus_interfaces M90_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M91_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 91} [ipx::get_bus_interfaces M91_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 91} [ipx::get_bus_interfaces M91_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 91} [ipx::get_bus_interfaces M91_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M92_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 92} [ipx::get_bus_interfaces M92_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 92} [ipx::get_bus_interfaces M92_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 92} [ipx::get_bus_interfaces M92_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M93_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 93} [ipx::get_bus_interfaces M93_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 93} [ipx::get_bus_interfaces M93_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 93} [ipx::get_bus_interfaces M93_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M94_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 94} [ipx::get_bus_interfaces M94_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 94} [ipx::get_bus_interfaces M94_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 94} [ipx::get_bus_interfaces M94_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M95_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 95} [ipx::get_bus_interfaces M95_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 95} [ipx::get_bus_interfaces M95_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 95} [ipx::get_bus_interfaces M95_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M96_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 96} [ipx::get_bus_interfaces M96_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 96} [ipx::get_bus_interfaces M96_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 96} [ipx::get_bus_interfaces M96_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M97_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 97} [ipx::get_bus_interfaces M97_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 97} [ipx::get_bus_interfaces M97_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 97} [ipx::get_bus_interfaces M97_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M98_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 98} [ipx::get_bus_interfaces M98_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 98} [ipx::get_bus_interfaces M98_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 98} [ipx::get_bus_interfaces M98_AXIS_areset -of_objects [ipx::current_core]]
ipx::infer_bus_interface M99_AXIS_areset xilinx.com:signal:reset_rtl:1.0 [ipx::current_core]
set_property enablement_dependency {$REPLICAS > 99} [ipx::get_bus_interfaces M99_AXIS -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 99} [ipx::get_bus_interfaces M99_AXIS_aclk -of_objects [ipx::current_core]]
set_property enablement_dependency {$REPLICAS > 99} [ipx::get_bus_interfaces M99_AXIS_areset -of_objects [ipx::current_core]]

ipx::check_integrity -quiet [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums [ipx::current_core]
ipx::save_core [ipx::current_core]
update_ip_catalog
close_project
