# Project
create_project AXI4_GPIO -in_memory -part xc7vx485tffg1157-1 -ip
set_property target_language VHDL [current_project]
set_property simulator_language VHDL [current_project]
set_property target_simulator XSim [current_project]
set_property ip_repo_paths [list ./IPs] [current_project]
add_files -norecurse {./Sources/Utils/Calc.vhd ./Sources/Utils/Types.vhd ./Sources/AXI4-GPIO/AXI4_GPIO_S_AXI.vhd ./Sources/AXI4-GPIO/AXI4_GPIO.vhd}
set_property file_type {VHDL 2008} [get_files ./Sources/AXI4-GPIO/AXI4_GPIO_S_AXI.vhd]
set_property file_type {VHDL 2008} [get_files ./Sources/AXI4-GPIO/AXI4_GPIO.vhd]
set_property top AXI4_GPIO [current_fileset]

# Create IP
ipx::package_project -root_dir ./IPs/AXI4-GPIO -import_files {./Sources/Utils/Calc.vhd ./Sources/AXI4-GPIO/AXI4_GPIO_S_AXI.vhd ./Sources/AXI4-GPIO/AXI4_GPIO.vhd} -vendor mohammad.ewais.ca -library ME_IPs -taxonomy {/AXI_Infrastructure}
set_property vendor_display_name {Mohammad Ewais} [ipx::current_core]
set_property name AXI4_GPIO [ipx::current_core]
set_property display_name {AXI4 GPIO v1.0} [ipx::current_core]
set_property description {AXI4 interfaced GPIO} [ipx::current_core]
set_property company_url {http://mohammad.ewais.ca} [ipx::current_core]
set_property vendor_display_name {Mohammad Ewais} [ipx::current_core]
set_property supported_families {virtex7 Production qvirtex7 Production kintex7 Production kintex7l Production qkintex7 Production qkintex7l Production artix7 Production artix7l Production aartix7 Production qartix7 Production zynq Production qzynq Production azynq Production spartan7 Production aspartan7 Production virtexu Production zynquplus Production virtexuplus Production virtexuplusHBM Production kintexuplus Production kintexu Production} [ipx::current_core]

# Params
set_property display_name {AXI ID Width} [ipgui::get_guiparamspec -name "C_S00_AXI_ID_WIDTH" -component [ipx::current_core] ]
set_property tooltip {Width of ID for for write address, write data, read address and read data} [ipgui::get_guiparamspec -name "C_S00_AXI_ID_WIDTH" -component [ipx::current_core] ]
set_property widget {textEdit} [ipgui::get_guiparamspec -name "C_S00_AXI_ID_WIDTH" -component [ipx::current_core] ]
set_property value 8 [ipx::get_user_parameters C_S00_AXI_ID_WIDTH -of_objects [ipx::current_core]]
set_property value 8 [ipx::get_hdl_parameters C_S00_AXI_ID_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_user_parameters C_S00_AXI_ID_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_hdl_parameters C_S00_AXI_ID_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_type range_long [ipx::get_user_parameters C_S00_AXI_ID_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_minimum 1 [ipx::get_user_parameters C_S00_AXI_ID_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_maximum 16 [ipx::get_user_parameters C_S00_AXI_ID_WIDTH -of_objects [ipx::current_core]]
ipx::update_dependency [ipx::get_user_parameters C_S00_AXI_ID_WIDTH -of_objects [ipx::current_core]]

set_property display_name {AXI AW User Width} [ipgui::get_guiparamspec -name "C_S00_AXI_AWUSER_WIDTH" -component [ipx::current_core] ]
set_property tooltip {Width of optional user defined signal in write address channel} [ipgui::get_guiparamspec -name "C_S00_AXI_AWUSER_WIDTH" -component [ipx::current_core] ]
set_property widget {textEdit} [ipgui::get_guiparamspec -name "C_S00_AXI_AWUSER_WIDTH" -component [ipx::current_core] ]
set_property value 0 [ipx::get_user_parameters C_S00_AXI_AWUSER_WIDTH -of_objects [ipx::current_core]]
set_property value 0 [ipx::get_hdl_parameters C_S00_AXI_AWUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_user_parameters C_S00_AXI_AWUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_hdl_parameters C_S00_AXI_AWUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_type range_long [ipx::get_user_parameters C_S00_AXI_AWUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_minimum 0 [ipx::get_user_parameters C_S00_AXI_AWUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_maximum 16 [ipx::get_user_parameters C_S00_AXI_AWUSER_WIDTH -of_objects [ipx::current_core]]
ipx::update_dependency [ipx::get_user_parameters C_S00_AXI_AWUSER_WIDTH -of_objects [ipx::current_core]]

set_property display_name {AXI AR User Width} [ipgui::get_guiparamspec -name "C_S00_AXI_ARUSER_WIDTH" -component [ipx::current_core] ]
set_property tooltip {Width of optional user defined signal in read address channel} [ipgui::get_guiparamspec -name "C_S00_AXI_ARUSER_WIDTH" -component [ipx::current_core] ]
set_property widget {textEdit} [ipgui::get_guiparamspec -name "C_S00_AXI_ARUSER_WIDTH" -component [ipx::current_core] ]
set_property value 0 [ipx::get_user_parameters C_S00_AXI_ARUSER_WIDTH -of_objects [ipx::current_core]]
set_property value 0 [ipx::get_hdl_parameters C_S00_AXI_ARUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_user_parameters C_S00_AXI_ARUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_hdl_parameters C_S00_AXI_ARUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_type range_long [ipx::get_user_parameters C_S00_AXI_ARUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_minimum 0 [ipx::get_user_parameters C_S00_AXI_ARUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_maximum 16 [ipx::get_user_parameters C_S00_AXI_ARUSER_WIDTH -of_objects [ipx::current_core]]
ipx::update_dependency [ipx::get_user_parameters C_S00_AXI_ARUSER_WIDTH -of_objects [ipx::current_core]]

set_property display_name {AXI W User Width} [ipgui::get_guiparamspec -name "C_S00_AXI_WUSER_WIDTH" -component [ipx::current_core] ]
set_property tooltip {Width of optional user defined signal in write channel} [ipgui::get_guiparamspec -name "C_S00_AXI_WUSER_WIDTH" -component [ipx::current_core] ]
set_property widget {textEdit} [ipgui::get_guiparamspec -name "C_S00_AXI_WUSER_WIDTH" -component [ipx::current_core] ]
set_property value 0 [ipx::get_user_parameters C_S00_AXI_WUSER_WIDTH -of_objects [ipx::current_core]]
set_property value 0 [ipx::get_hdl_parameters C_S00_AXI_WUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_user_parameters C_S00_AXI_WUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_hdl_parameters C_S00_AXI_WUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_type range_long [ipx::get_user_parameters C_S00_AXI_WUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_minimum 0 [ipx::get_user_parameters C_S00_AXI_WUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_maximum 16 [ipx::get_user_parameters C_S00_AXI_WUSER_WIDTH -of_objects [ipx::current_core]]
ipx::update_dependency [ipx::get_user_parameters C_S00_AXI_WUSER_WIDTH -of_objects [ipx::current_core]]

set_property display_name {AXI R User Width} [ipgui::get_guiparamspec -name "C_S00_AXI_RUSER_WIDTH" -component [ipx::current_core] ]
set_property tooltip {Width of optional user defined signal in read channel} [ipgui::get_guiparamspec -name "C_S00_AXI_RUSER_WIDTH" -component [ipx::current_core] ]
set_property widget {textEdit} [ipgui::get_guiparamspec -name "C_S00_AXI_RUSER_WIDTH" -component [ipx::current_core] ]
set_property value 0 [ipx::get_user_parameters C_S00_AXI_RUSER_WIDTH -of_objects [ipx::current_core]]
set_property value 0 [ipx::get_hdl_parameters C_S00_AXI_RUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_user_parameters C_S00_AXI_RUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_hdl_parameters C_S00_AXI_RUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_type range_long [ipx::get_user_parameters C_S00_AXI_RUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_minimum 0 [ipx::get_user_parameters C_S00_AXI_RUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_maximum 16 [ipx::get_user_parameters C_S00_AXI_RUSER_WIDTH -of_objects [ipx::current_core]]
ipx::update_dependency [ipx::get_user_parameters C_S00_AXI_RUSER_WIDTH -of_objects [ipx::current_core]]

set_property display_name {AXI B User Width} [ipgui::get_guiparamspec -name "C_S00_AXI_BUSER_WIDTH" -component [ipx::current_core] ]
set_property tooltip {Width of optional user defined signal in write response channel} [ipgui::get_guiparamspec -name "C_S00_AXI_BUSER_WIDTH" -component [ipx::current_core] ]
set_property widget {textEdit} [ipgui::get_guiparamspec -name "C_S00_AXI_BUSER_WIDTH" -component [ipx::current_core] ]
set_property value 0 [ipx::get_user_parameters C_S00_AXI_BUSER_WIDTH -of_objects [ipx::current_core]]
set_property value 0 [ipx::get_hdl_parameters C_S00_AXI_BUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_user_parameters C_S00_AXI_BUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_hdl_parameters C_S00_AXI_BUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_type range_long [ipx::get_user_parameters C_S00_AXI_BUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_minimum 0 [ipx::get_user_parameters C_S00_AXI_BUSER_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_range_maximum 16 [ipx::get_user_parameters C_S00_AXI_BUSER_WIDTH -of_objects [ipx::current_core]]
ipx::update_dependency [ipx::get_user_parameters C_S00_AXI_BUSER_WIDTH -of_objects [ipx::current_core]]

set_property display_name {Width} [ipgui::get_guiparamspec -name "GPIO_WIDTH" -component [ipx::current_core] ]
set_property tooltip {Width of your GPIO, in bits} [ipgui::get_guiparamspec -name "GPIO_WIDTH" -component [ipx::current_core] ]
set_property widget {comboBox} [ipgui::get_guiparamspec -name "GPIO_WIDTH" -component [ipx::current_core] ]
set_property value 32 [ipx::get_user_parameters GPIO_WIDTH -of_objects [ipx::current_core]]
set_property value 32 [ipx::get_hdl_parameters GPIO_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_user_parameters GPIO_WIDTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_hdl_parameters GPIO_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_type list [ipx::get_user_parameters GPIO_WIDTH -of_objects [ipx::current_core]]
set_property value_validation_list {8 16 32 64 128 256 512} [ipx::get_user_parameters GPIO_WIDTH -of_objects [ipx::current_core]]

set_property display_name {Number of GPIOs} [ipgui::get_guiparamspec -name "GPIO_DEPTH" -component [ipx::current_core] ]
set_property tooltip {Number of GPIOs} [ipgui::get_guiparamspec -name "GPIO_DEPTH" -component [ipx::current_core] ]
set_property widget {comboBox} [ipgui::get_guiparamspec -name "GPIO_DEPTH" -component [ipx::current_core] ]
set_property value 64 [ipx::get_user_parameters GPIO_DEPTH -of_objects [ipx::current_core]]
set_property value 64 [ipx::get_hdl_parameters GPIO_DEPTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_user_parameters GPIO_DEPTH -of_objects [ipx::current_core]]
set_property value_format long [ipx::get_hdl_parameters GPIO_DEPTH -of_objects [ipx::current_core]]
set_property value_validation_type list [ipx::get_user_parameters GPIO_DEPTH -of_objects [ipx::current_core]]
set_property value_validation_list {2 4 8 16 32 64 128 256 512 1024 2048 4096} [ipx::get_user_parameters GPIO_DEPTH -of_objects [ipx::current_core]]

ipgui::add_param -name {C_S00_AXI_DATA_WIDTH} -component [ipx::current_core]
set_property display_name {AXI Data Width} [ipgui::get_guiparamspec -name "C_S00_AXI_DATA_WIDTH" -component [ipx::current_core] ]
set_property tooltip {Width of AXI Data word} [ipgui::get_guiparamspec -name "C_S00_AXI_DATA_WIDTH" -component [ipx::current_core] ]
set_property widget {textEdit} [ipgui::get_guiparamspec -name "C_S00_AXI_DATA_WIDTH" -component [ipx::current_core] ]
set_property enablement_value false [ipx::get_user_parameters C_S00_AXI_DATA_WIDTH -of_objects [ipx::current_core]]
set_property value_tcl_expr {$GPIO_WIDTH} [ipx::get_user_parameters C_S00_AXI_DATA_WIDTH -of_objects [ipx::current_core]]
set_property value 32 [ipx::get_user_parameters C_S00_AXI_DATA_WIDTH -of_objects [ipx::current_core]]

set_property display_name {AXI Addr Width} [ipgui::get_guiparamspec -name "C_S00_AXI_ADDR_WIDTH" -component [ipx::current_core] ]
set_property tooltip {Width of AXI address} [ipgui::get_guiparamspec -name "C_S00_AXI_ADDR_WIDTH" -component [ipx::current_core] ]
set_property widget {textEdit} [ipgui::get_guiparamspec -name "C_S00_AXI_ADDR_WIDTH" -component [ipx::current_core] ]
set_property enablement_value false [ipx::get_user_parameters C_S00_AXI_ADDR_WIDTH -of_objects [ipx::current_core]]
set_property value_tcl_expr {(log($GPIO_WIDTH/8)/log(2))+(log($GPIO_DEPTH)/log(2))} [ipx::get_user_parameters C_S00_AXI_ADDR_WIDTH -of_objects [ipx::current_core]]
set_property value 8 [ipx::get_user_parameters C_S00_AXI_ADDR_WIDTH -of_objects [ipx::current_core]]
set_property value 8 [ipx::get_hdl_parameters C_S00_AXI_ADDR_WIDTH -of_objects [ipx::current_core]]

# GUI
ipgui::add_group -name {GPIOs} -component [ipx::current_core] -parent [ipgui::get_pagespec -name "Page 0" -component [ipx::current_core] ] -display_name {GPIOs}
ipgui::add_group -name {AXI interface} -component [ipx::current_core] -parent [ipgui::get_pagespec -name "Page 0" -component [ipx::current_core] ] -display_name {AXI interface}
ipgui::move_param -component [ipx::current_core] -order 0 [ipgui::get_guiparamspec -name "GPIO_WIDTH" -component [ipx::current_core]] -parent [ipgui::get_groupspec -name "GPIOs" -component [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 1 [ipgui::get_guiparamspec -name "GPIO_DEPTH" -component [ipx::current_core]] -parent [ipgui::get_groupspec -name "GPIOs" -component [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 0 [ipgui::get_guiparamspec -name "C_S00_AXI_ID_WIDTH" -component [ipx::current_core]] -parent [ipgui::get_groupspec -name "AXI interface" -component [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 1 [ipgui::get_guiparamspec -name "C_S00_AXI_ADDR_WIDTH" -component [ipx::current_core]] -parent [ipgui::get_groupspec -name "AXI interface" -component [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 2 [ipgui::get_guiparamspec -name "C_S00_AXI_DATA_WIDTH" -component [ipx::current_core]] -parent [ipgui::get_groupspec -name "AXI interface" -component [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 3 [ipgui::get_guiparamspec -name "C_S00_AXI_AWUSER_WIDTH" -component [ipx::current_core]] -parent [ipgui::get_groupspec -name "AXI interface" -component [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 4 [ipgui::get_guiparamspec -name "C_S00_AXI_ARUSER_WIDTH" -component [ipx::current_core]] -parent [ipgui::get_groupspec -name "AXI interface" -component [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 5 [ipgui::get_guiparamspec -name "C_S00_AXI_WUSER_WIDTH" -component [ipx::current_core]] -parent [ipgui::get_groupspec -name "AXI interface" -component [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 6 [ipgui::get_guiparamspec -name "C_S00_AXI_RUSER_WIDTH" -component [ipx::current_core]] -parent [ipgui::get_groupspec -name "AXI interface" -component [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 7 [ipgui::get_guiparamspec -name "C_S00_AXI_BUSER_WIDTH" -component [ipx::current_core]] -parent [ipgui::get_groupspec -name "AXI interface" -component [ipx::current_core]]

set_property driver_value 0 [ipx::get_ports GPIO_001_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 1} [ipx::get_ports GPIO_001_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 1} [ipx::get_ports GPIO_001_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_002_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 2} [ipx::get_ports GPIO_002_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 2} [ipx::get_ports GPIO_002_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_003_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 3} [ipx::get_ports GPIO_003_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 3} [ipx::get_ports GPIO_003_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_004_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 4} [ipx::get_ports GPIO_004_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 4} [ipx::get_ports GPIO_004_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_005_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 5} [ipx::get_ports GPIO_005_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 5} [ipx::get_ports GPIO_005_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_006_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 6} [ipx::get_ports GPIO_006_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 6} [ipx::get_ports GPIO_006_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_007_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 7} [ipx::get_ports GPIO_007_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 7} [ipx::get_ports GPIO_007_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_008_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 8} [ipx::get_ports GPIO_008_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 8} [ipx::get_ports GPIO_008_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_009_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 9} [ipx::get_ports GPIO_009_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 9} [ipx::get_ports GPIO_009_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_010_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 10} [ipx::get_ports GPIO_010_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 10} [ipx::get_ports GPIO_010_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_011_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 11} [ipx::get_ports GPIO_011_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 11} [ipx::get_ports GPIO_011_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_012_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 12} [ipx::get_ports GPIO_012_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 12} [ipx::get_ports GPIO_012_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_013_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 13} [ipx::get_ports GPIO_013_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 13} [ipx::get_ports GPIO_013_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_014_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 14} [ipx::get_ports GPIO_014_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 14} [ipx::get_ports GPIO_014_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_015_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 15} [ipx::get_ports GPIO_015_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 15} [ipx::get_ports GPIO_015_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_016_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 16} [ipx::get_ports GPIO_016_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 16} [ipx::get_ports GPIO_016_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_017_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 17} [ipx::get_ports GPIO_017_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 17} [ipx::get_ports GPIO_017_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_018_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 18} [ipx::get_ports GPIO_018_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 18} [ipx::get_ports GPIO_018_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_019_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 19} [ipx::get_ports GPIO_019_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 19} [ipx::get_ports GPIO_019_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_020_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 20} [ipx::get_ports GPIO_020_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 20} [ipx::get_ports GPIO_020_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_021_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 21} [ipx::get_ports GPIO_021_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 21} [ipx::get_ports GPIO_021_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_022_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 22} [ipx::get_ports GPIO_022_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 22} [ipx::get_ports GPIO_022_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_023_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 23} [ipx::get_ports GPIO_023_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 23} [ipx::get_ports GPIO_023_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_024_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 24} [ipx::get_ports GPIO_024_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 24} [ipx::get_ports GPIO_024_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_025_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 25} [ipx::get_ports GPIO_025_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 25} [ipx::get_ports GPIO_025_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_026_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 26} [ipx::get_ports GPIO_026_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 26} [ipx::get_ports GPIO_026_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_027_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 27} [ipx::get_ports GPIO_027_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 27} [ipx::get_ports GPIO_027_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_028_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 28} [ipx::get_ports GPIO_028_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 28} [ipx::get_ports GPIO_028_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_029_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 29} [ipx::get_ports GPIO_029_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 29} [ipx::get_ports GPIO_029_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_030_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 30} [ipx::get_ports GPIO_030_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 30} [ipx::get_ports GPIO_030_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_031_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 31} [ipx::get_ports GPIO_031_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 31} [ipx::get_ports GPIO_031_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_032_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 32} [ipx::get_ports GPIO_032_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 32} [ipx::get_ports GPIO_032_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_033_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 33} [ipx::get_ports GPIO_033_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 33} [ipx::get_ports GPIO_033_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_034_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 34} [ipx::get_ports GPIO_034_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 34} [ipx::get_ports GPIO_034_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_035_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 35} [ipx::get_ports GPIO_035_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 35} [ipx::get_ports GPIO_035_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_036_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 36} [ipx::get_ports GPIO_036_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 36} [ipx::get_ports GPIO_036_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_037_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 37} [ipx::get_ports GPIO_037_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 37} [ipx::get_ports GPIO_037_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_038_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 38} [ipx::get_ports GPIO_038_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 38} [ipx::get_ports GPIO_038_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_039_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 39} [ipx::get_ports GPIO_039_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 39} [ipx::get_ports GPIO_039_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_040_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 40} [ipx::get_ports GPIO_040_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 40} [ipx::get_ports GPIO_040_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_041_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 41} [ipx::get_ports GPIO_041_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 41} [ipx::get_ports GPIO_041_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_042_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 42} [ipx::get_ports GPIO_042_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 42} [ipx::get_ports GPIO_042_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_043_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 43} [ipx::get_ports GPIO_043_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 43} [ipx::get_ports GPIO_043_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_044_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 44} [ipx::get_ports GPIO_044_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 44} [ipx::get_ports GPIO_044_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_045_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 45} [ipx::get_ports GPIO_045_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 45} [ipx::get_ports GPIO_045_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_046_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 46} [ipx::get_ports GPIO_046_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 46} [ipx::get_ports GPIO_046_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_047_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 47} [ipx::get_ports GPIO_047_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 47} [ipx::get_ports GPIO_047_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_048_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 48} [ipx::get_ports GPIO_048_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 48} [ipx::get_ports GPIO_048_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_049_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 49} [ipx::get_ports GPIO_049_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 49} [ipx::get_ports GPIO_049_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_050_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 50} [ipx::get_ports GPIO_050_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 50} [ipx::get_ports GPIO_050_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_051_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 51} [ipx::get_ports GPIO_051_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 51} [ipx::get_ports GPIO_051_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_052_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 52} [ipx::get_ports GPIO_052_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 52} [ipx::get_ports GPIO_052_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_053_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 53} [ipx::get_ports GPIO_053_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 53} [ipx::get_ports GPIO_053_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_054_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 54} [ipx::get_ports GPIO_054_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 54} [ipx::get_ports GPIO_054_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_055_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 55} [ipx::get_ports GPIO_055_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 55} [ipx::get_ports GPIO_055_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_056_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 56} [ipx::get_ports GPIO_056_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 56} [ipx::get_ports GPIO_056_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_057_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 57} [ipx::get_ports GPIO_057_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 57} [ipx::get_ports GPIO_057_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_058_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 58} [ipx::get_ports GPIO_058_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 58} [ipx::get_ports GPIO_058_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_059_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 59} [ipx::get_ports GPIO_059_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 59} [ipx::get_ports GPIO_059_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_060_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 60} [ipx::get_ports GPIO_060_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 60} [ipx::get_ports GPIO_060_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_061_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 61} [ipx::get_ports GPIO_061_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 61} [ipx::get_ports GPIO_061_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_062_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 62} [ipx::get_ports GPIO_062_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 62} [ipx::get_ports GPIO_062_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_063_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 63} [ipx::get_ports GPIO_063_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 63} [ipx::get_ports GPIO_063_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_064_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 64} [ipx::get_ports GPIO_064_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 64} [ipx::get_ports GPIO_064_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_065_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 65} [ipx::get_ports GPIO_065_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 65} [ipx::get_ports GPIO_065_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_066_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 66} [ipx::get_ports GPIO_066_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 66} [ipx::get_ports GPIO_066_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_067_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 67} [ipx::get_ports GPIO_067_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 67} [ipx::get_ports GPIO_067_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_068_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 68} [ipx::get_ports GPIO_068_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 68} [ipx::get_ports GPIO_068_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_069_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 69} [ipx::get_ports GPIO_069_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 69} [ipx::get_ports GPIO_069_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_070_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 70} [ipx::get_ports GPIO_070_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 70} [ipx::get_ports GPIO_070_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_071_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 71} [ipx::get_ports GPIO_071_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 71} [ipx::get_ports GPIO_071_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_072_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 72} [ipx::get_ports GPIO_072_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 72} [ipx::get_ports GPIO_072_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_073_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 73} [ipx::get_ports GPIO_073_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 73} [ipx::get_ports GPIO_073_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_074_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 74} [ipx::get_ports GPIO_074_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 74} [ipx::get_ports GPIO_074_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_075_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 75} [ipx::get_ports GPIO_075_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 75} [ipx::get_ports GPIO_075_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_076_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 76} [ipx::get_ports GPIO_076_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 76} [ipx::get_ports GPIO_076_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_077_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 77} [ipx::get_ports GPIO_077_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 77} [ipx::get_ports GPIO_077_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_078_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 78} [ipx::get_ports GPIO_078_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 78} [ipx::get_ports GPIO_078_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_079_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 79} [ipx::get_ports GPIO_079_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 79} [ipx::get_ports GPIO_079_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_080_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 80} [ipx::get_ports GPIO_080_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 80} [ipx::get_ports GPIO_080_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_081_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 81} [ipx::get_ports GPIO_081_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 81} [ipx::get_ports GPIO_081_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_082_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 82} [ipx::get_ports GPIO_082_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 82} [ipx::get_ports GPIO_082_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_083_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 83} [ipx::get_ports GPIO_083_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 83} [ipx::get_ports GPIO_083_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_084_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 84} [ipx::get_ports GPIO_084_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 84} [ipx::get_ports GPIO_084_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_085_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 85} [ipx::get_ports GPIO_085_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 85} [ipx::get_ports GPIO_085_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_086_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 86} [ipx::get_ports GPIO_086_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 86} [ipx::get_ports GPIO_086_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_087_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 87} [ipx::get_ports GPIO_087_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 87} [ipx::get_ports GPIO_087_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_088_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 88} [ipx::get_ports GPIO_088_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 88} [ipx::get_ports GPIO_088_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_089_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 89} [ipx::get_ports GPIO_089_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 89} [ipx::get_ports GPIO_089_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_090_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 90} [ipx::get_ports GPIO_090_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 90} [ipx::get_ports GPIO_090_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_091_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 91} [ipx::get_ports GPIO_091_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 91} [ipx::get_ports GPIO_091_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_092_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 92} [ipx::get_ports GPIO_092_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 92} [ipx::get_ports GPIO_092_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_093_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 93} [ipx::get_ports GPIO_093_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 93} [ipx::get_ports GPIO_093_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_094_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 94} [ipx::get_ports GPIO_094_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 94} [ipx::get_ports GPIO_094_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_095_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 95} [ipx::get_ports GPIO_095_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 95} [ipx::get_ports GPIO_095_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_096_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 96} [ipx::get_ports GPIO_096_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 96} [ipx::get_ports GPIO_096_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_097_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 97} [ipx::get_ports GPIO_097_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 97} [ipx::get_ports GPIO_097_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_098_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 98} [ipx::get_ports GPIO_098_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 98} [ipx::get_ports GPIO_098_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_099_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 99} [ipx::get_ports GPIO_099_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 99} [ipx::get_ports GPIO_099_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_100_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 100} [ipx::get_ports GPIO_100_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 100} [ipx::get_ports GPIO_100_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_101_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 101} [ipx::get_ports GPIO_101_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 101} [ipx::get_ports GPIO_101_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_102_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 102} [ipx::get_ports GPIO_102_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 102} [ipx::get_ports GPIO_102_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_103_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 103} [ipx::get_ports GPIO_103_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 103} [ipx::get_ports GPIO_103_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_104_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 104} [ipx::get_ports GPIO_104_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 104} [ipx::get_ports GPIO_104_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_105_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 105} [ipx::get_ports GPIO_105_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 105} [ipx::get_ports GPIO_105_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_106_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 106} [ipx::get_ports GPIO_106_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 106} [ipx::get_ports GPIO_106_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_107_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 107} [ipx::get_ports GPIO_107_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 107} [ipx::get_ports GPIO_107_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_108_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 108} [ipx::get_ports GPIO_108_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 108} [ipx::get_ports GPIO_108_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_109_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 109} [ipx::get_ports GPIO_109_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 109} [ipx::get_ports GPIO_109_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_110_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 110} [ipx::get_ports GPIO_110_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 110} [ipx::get_ports GPIO_110_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_111_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 111} [ipx::get_ports GPIO_111_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 111} [ipx::get_ports GPIO_111_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_112_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 112} [ipx::get_ports GPIO_112_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 112} [ipx::get_ports GPIO_112_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_113_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 113} [ipx::get_ports GPIO_113_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 113} [ipx::get_ports GPIO_113_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_114_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 114} [ipx::get_ports GPIO_114_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 114} [ipx::get_ports GPIO_114_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_115_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 115} [ipx::get_ports GPIO_115_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 115} [ipx::get_ports GPIO_115_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_116_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 116} [ipx::get_ports GPIO_116_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 116} [ipx::get_ports GPIO_116_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_117_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 117} [ipx::get_ports GPIO_117_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 117} [ipx::get_ports GPIO_117_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_118_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 118} [ipx::get_ports GPIO_118_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 118} [ipx::get_ports GPIO_118_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_119_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 119} [ipx::get_ports GPIO_119_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 119} [ipx::get_ports GPIO_119_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_120_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 120} [ipx::get_ports GPIO_120_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 120} [ipx::get_ports GPIO_120_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_121_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 121} [ipx::get_ports GPIO_121_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 121} [ipx::get_ports GPIO_121_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_122_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 122} [ipx::get_ports GPIO_122_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 122} [ipx::get_ports GPIO_122_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_123_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 123} [ipx::get_ports GPIO_123_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 123} [ipx::get_ports GPIO_123_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_124_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 124} [ipx::get_ports GPIO_124_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 124} [ipx::get_ports GPIO_124_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_125_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 125} [ipx::get_ports GPIO_125_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 125} [ipx::get_ports GPIO_125_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_126_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 126} [ipx::get_ports GPIO_126_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 126} [ipx::get_ports GPIO_126_OUT -of_objects [ipx::current_core]]
set_property driver_value 0 [ipx::get_ports GPIO_127_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 127} [ipx::get_ports GPIO_127_IN -of_objects [ipx::current_core]]
set_property enablement_dependency {$GPIO_DEPTH > 127} [ipx::get_ports GPIO_127_OUT -of_objects [ipx::current_core]]

ipx::check_integrity -quiet [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums [ipx::current_core]
ipx::save_core [ipx::current_core]
update_ip_catalog
close_project
